module: SwiftVersionCompare
author: mflknr
author_url: https://www.mflknr.de/
github_url: https://github.com/mflknr/SwiftVersionCompare/
readme: README.md
skip_undocumented: true
hide_documentation_coverage: false
theme: apple
output: docs/
swift_version: 5.3.2
clean: true
min_acl: public
xcodebuild_arguments:
  - -project
  - SwiftVersionCompare.xcodeproj
  - -scheme
  - SwiftVersionCompare-Package

