name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift --version
    - run: swift build -v
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift --version
    - name: Generate Project
      run: swift package generate-xcodeproj --enable-code-coverage
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SwiftVersionCompare.xcodeproj
        scheme: SwiftVersionCompare-Package
        action: test
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        verbose: true
