name: builds

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - '**.swift'
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        swift: [ "6.0" ]
        xcode: [ "16.4.0" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
  
      - run: swift build -v
      - run: swift test -v
