name: check build and tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        swift: ["5.7", "5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      
      - run: swift --version
      - run: swift build -v
      - run: swift test -v