name: Check build and tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.3", "5.4", "5.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift Environment for Ubuntu and macOS
        uses: fwal/setup-swift@v1.7.0
        with:
          swift-version: ${{ matrix.swift }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          swift --version
          swift build -v
        
  test:
    name: Test with Swift ${{ matrix.swift }}
    strategy:
      matrix:
        os: [ macos-latest ]
        swift: ["5.3", "5.4", "5.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift Environment
        uses: fwal/setup-swift@v1.7.0
        with:
          swift-version: ${{ matrix.swift }}
          
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Test
        run: |
          swift --version
          swift test
        
  codecov:
    name: Deploy to Codecov
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1.4
        with:
          project: SwiftVersionCompare.xcodeproj
          scheme: SwiftVersionCompare-Package
          action: test
          
      - name: Deploy to Codecov
        uses: codecov/codecov-action@v1
