name: Check build and tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        swift: ["5.7", "5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift Environment for Ubuntu and macOS
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v