name: update-docs

on:
  push:
    branches: [ main ]

jobs:
  document:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: generate docs
        uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          output: docs

      - name: deploy docs to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: documentation
          folder: docs
