name: lint

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v4
     - uses: jdx/mise-action@v2
     - run: swiftlint --strict
     - run: swiftformat . --lint --strict