name: Check build and tests

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift Environment for Ubuntu and macOS
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Swift Version
        run: swift --version
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: swift build -v