name: release

on:
  workflow_dispatch:
  push:
    tags: 
      - '*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          skipIfReleaseExists: true
          bodyFile: "CHANGELOG.md"

