name: Create Release

on:
  push:
    tags: 
      - '*'

jobs:
  release:
    runs-on: macos-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Get current tag
      id: vars
      run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      
    - name: Release to GitHub
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        title: "[${{ steps.vars.outputs.tag }}] - ${{ steps.date.outputs.date }}"
