name: release

on:
  push:
    branches:
      - main
    tags: 
      - '*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          skipIfReleaseExists: true

