name: release

on:
  push:
    tags: 
      - '*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          skipIfReleaseExists: true

