name: Release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  release:
    runs-on: macos-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Get current tag
      id: vars
      run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        title: "[${{ steps.vars.outputs.tag }}] - ${{ steps.date.outputs.date }}"
