name: Update Documentation

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: swift build -v
  document:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - name: Generate Documentation
        uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          output: docs
      - name: Upload generated Documentation
        run: git checkout documentation
      - run: git checkout main -- docs
      - run: git add docs
      - run: git commit -m "Adding 'docs' directory from 'main' branch."
