name: Update Documentation

on:
  push:
    branches: [ main ]

jobs:
  document:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote update
          git fetch --all
          git checkout origin/main
      - name: Generate Documentation
        uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          output: docs
      - name: Push generated Documentation to dedicated branch
        run: |
          git stash
          git checkout origin/documentation
          git stash pop
          git commit -m "docs: automatically generate documentation from 'main'"
          git push
