name: Update Documentation on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: swift build -v
  document:
    runs-on: macos-latest
    steps:
      - uses: sersoft-gmbh/swifty-docs-action@v1
  upload:
    runs-on: macos-latest
    steps:
      - name: upload
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: documentation
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
