name: Update Documentation

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: swift build -v
  document:
    runs-on: macos-latest
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
      - name: Install jazzy
        run: gem install jazzy
      - name: Generate Documentation
        run: jazzy
      - name: Upload generated Documentation
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: documentation
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
