name: Update Documentation

on:
  push:
    branches: [ main ]

jobs:
  document:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate Documentation
        uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          output: docs

      - name: Deploy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: documentation
          folder: docs
